Update workflow.yml

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -2,33 +2,39 @@ name: Download CS Game Files
 
 on:
   schedule:
-  - cron: "0 6 * * *"
-
+    - cron: "0 */4 * * *"
   workflow_dispatch:
 
 jobs: 
-    download:
-      runs-on: ubuntu-latest
+  download:
+    runs-on: ubuntu-latest
       
-      permissions:
-        # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
-        contents: write
+    permissions:
+      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
+      contents: write
       
-      steps:
-        - uses: actions/checkout@master
-        - uses: actions/setup-node@v3
-        - name: Download new game files
-          run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
-        - name: Run Decompiler for pak01_dir.vpk with ValveResourceFormat 8.1
-          run: |
-            chmod +x ./Decompiler
-            ./Decompiler -i "./temp/pak01_dir.vpk" -o "./static" -e "vtex_c" -d -f "panorama/images/econ"
-        - name: Read manifestId.txt
-          id: manifestId
-          uses: juliangruber/read-file-action@v1
-          with:
-            path: ./static/manifestId.txt
-        - name: Commit & push changes
-          uses: stefanzweifel/git-auto-commit-action@v4
-          with:
-            commit_message: "manifest ${{ steps.manifestId.outputs.content }}"
+    steps:
+      - uses: actions/checkout@master
+      - uses: actions/setup-node@v3
+      - name: Download new game files
+        run: npm install && node index.js '${{ secrets.USERNAME }}' '${{ secrets.PASSWORD }}'
+      - name: Check if pak01_dir.vpk exists
+        run: |
+          if [ ! -f temp/pak01_dir.vpk ]; then
+            echo "pak01_dir.vpk not found"
+            exit 1
+          fi
+      - name: Run Decompiler for pak01_dir.vpk with ValveResourceFormat 8.1
+        if: success()
+        run: |
+          chmod +x ./Decompiler
+          ./Decompiler -i "./temp/pak01_dir.vpk" -o "./static" -e "vtex_c" -d -f "panorama/images/econ"
+      - name: Read manifestId.txt
+        id: manifestId
+        uses: juliangruber/read-file-action@v1
+        with:
+          path: ./static/manifestId.txt
+      - name: Commit & push changes
+        uses: stefanzweifel/git-auto-commit-action@v4
+        with:
+          commit_message: "manifest ${{ steps.manifestId.outputs.content }}"
